# fly.toml app configuration file generated for fs-patientor on 2024-06-09T14:05:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fs-patientor'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
